# Numpy

In [4]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5])

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
print(arr)

[1 2 3 4 5]


In [8]:
print(arr.ndim)#dimension of arr

1


In [9]:
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
print(arr.shape)

(5,)


In [11]:
arr1=np.array([[1,2,3],[4,5,6]])

In [12]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [13]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
print(arr1.shape)

(2, 3)


In [15]:
print(arr1.ndim)#dimension of arr1

2


In [16]:
arr2=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])

In [17]:
arr2

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [18]:
print(arr2)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [19]:
print(arr2.shape)

(2, 2, 2)


In [20]:
print(arr2.ndim)#dimension of arr2

3


In [21]:
#accessing index

In [22]:
ar1=np.array([29,90,50,57])

In [23]:
ar1[3]

57

In [24]:
ar2=np.array([[29,90,50,57],[29,90,50,57]])

In [26]:
ar2[2,2]

IndexError: index 2 is out of bounds for axis 0 with size 2

# random number using numpy

In [53]:
from numpy import random as r

In [56]:
/x=r.randint(100)

In [57]:
x

48

# Creating random array

In [66]:
y=r.randint(100,size=(50))

In [67]:
y

array([37, 27, 50, 97, 52, 34, 22, 46, 19, 94, 86, 96, 71,  0,  7, 72, 54,
       80, 59, 61, 66, 73, 53, 18, 75, 32, 61, 70, 90, 81, 39, 39, 47, 21,
       59, 26, 45, 76, 77, 73, 92, 85, 68, 30, 90, 43, 87, 97, 60, 28])

In [68]:
#2D random array

In [69]:
a=r.randint(100,size=(5,3))

In [70]:
a

array([[96, 18, 57],
       [18, 48,  6],
       [73, 25, 50],
       [39, 47, 93],
       [72, 65, 56]])

In [71]:
#3D random array

In [74]:
b=r.randint(100,size=(5,3,2))

In [75]:
b

array([[[17, 31],
        [67, 31],
        [77, 59]],

       [[89, 52],
        [ 8, 30],
        [84, 48]],

       [[88, 66],
        [27, 10],
        [64, 14]],

       [[ 7, 24],
        [14, 77],
        [31, 35]],

       [[57, 49],
        [85, 11],
        [97, 18]]])

# Linespace----divide values in equal parts

In [87]:
lp=np.linspace(0,2,10)

In [88]:
lp

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])